name: Build and Release LLVM for torchsim

on:
  push:
    tags:
      - 'v*.*.*'  # Matches version tags like v1.0.0

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: write

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout llvm-project
        uses: actions/checkout@v4
        with:
          repository: PSAL-POSTECH/llvm-project
          ref: ${{ github.ref_name }}
          path: llvm-project

      - name: Debug1
        run: ls ${{ github.workspace }} -al && ls ${{ github.workspace }}/llvm-project -al

      - name: Build LLVM
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace/llvm-project \
          -u $(id -u):$(id -g) \
          ghcr.io/gem5/ubuntu-22.04_all-dependencies:latest \
          bash -c "
            mkdir -p build && cd build &&
            cmake -DLLVM_ENABLE_PROJECTS=mlir -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/workspace/llvm-project/riscv-llvm -DLLVM_TARGETS_TO_BUILD=RISCV -G \"Unix Makefiles\" ../llvm &&
            make -j && make install"

      - name: Debug2
        run: ls ${{ github.workspace }} -al

      - name: Archive Build Artifacts
        run: tar -czvf riscv-llvm-release.tar.gz -C ${{ github.workspace }}/llvm-project riscv-llvm

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: riscv-llvm-release.tar.gz